### PR TITLE
a fix for #14 and some minor tweaks i think might be nice 

### PR DESCRIPTION
**Pull request by igorlogius**
fix(#14): playback in private window
fix: remove external font nunito dependencies
feat: add shortcuts to show current song info, toggle favorite, toggle radio type, save song info

### CODE REVIEW

**Comment by pilar6195** [comment]
My bad. I looked over this PR and meant to test it locally but ended up forgetting. Looks good at first glance. Give me a day or two to test and I'll get back to you.

**Comment by igorlogius** [comment]
Thanks for re-opening and taking a look at this. 
Hope you find it at least mostly ok.  


By the way, i also have some local modifications to the preferences (aka. options) page ... which i think look a little nicer than the current one.  

If you want, i can make a PR for that too. 

Preview: 

snip_20230325-105307

**Comment by igorlogius** [comment]
Sadly i found an issue myself with the jpop/kpop type switching, but because i already delete the original fork repo (because i wasent expecting a reply) now i can not modify this PR. 

So i guess the simplest solution is if i'll just close this PR and open another with the fix. 

Sorry for the trouble.

**Comment by igorlogius** [comment]
@pilar6195 
You can preview and test the new fixed and modified version here:

https://addons.mozilla.org/en-US/firefox/addon/listen-moe-player/

- I like to test my stuff under real conditions, since i've had some suprises with web-ext debug builds and sideloaded extensions. 

- I might have overdone it a bit with the modifications, since besides the styling and some of the core aspects of the radio object not much has been left untouched. 

- Sorry if some of the UI stuff looks a bit off. I am not that good with CSS. 

After you give me some feedback and we make a couple of rounds preliminary changes and bugfixes then i'll see how to best make a PR out of it.

**Comment by pilar6195** [comment]
Could you create a PR with your new changes so I can look it over?

**Comment by igorlogius** [comment]
You can look it at it over here: 
https://github.com/igorlogius/listen-moe-player

**Comment by Pitu** [comment]
@igorlogius sorry but that's a lot of work to go through, could you open a PR instead so that we can see the changes and go through them? Otherwise checking your entire repo is a bit much.

**Pull request closed without merging**
